### ISSUE TITLE
Field::select method generate an empty option ever

### ISSUE THREAD

**Issue by nonDeath** [StydeNet/html#47]
Field::select method generate an empty option ever. I include placehoder key but the empty option still is generated.

**Comment by nonDeath** [comment]
Sorry, but adding the empty option it work fine!

**Comment by nonDeath** [comment]
Just, in my opinion placeholder key option must be more usefull in this case to be consistent with laravelcollective/html package.

**Comment by sileence** [comment]
what do you mean @nonDeath ?

**Comment by nonDeath** [comment]
Is hard to explain but i try...

When I use 

```
Field::select('my_select', ['1' => 'opt 1', '2' => 'opt 2'], 1);
```
I get a select with 2 options plus an empty option without text and value. I think, this behavior is not the expected for me, just i want have a select with only two options.

This behavior is ever performed when the FieldBuilder class render a select, it just add an empty item even when it not is specified on the arguments passed.

**Comment by sileence** [comment]
Set the `validation.empty_option.default` language key to false, i.e.:

// lang/es/validation.php
```
return [
    'empty_option' => [
        'default' => false;
    ]
];
```

That will remove all the empty options in all the selects, you can also do that by key (specifying the field name instead of default).

You can also assign the default to be something else like "Please select something", etc.

**Comment by nonDeath** [comment]
Great, i try with this. Thanks in adcance!
